import { Flight } from './flight';
export const FLIGHTS: Flight[] = [
    {id: 11, flightNumber : 'FS1298', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
    departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
    {id: 12, flightNumber : 'FS1201', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
    departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
    {id: 13, flightNumber : 'FS1211', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
    departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
  {id: 14, flightNumber : 'FS2211', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
    departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
  {id: 1, flightNumber : 'FS2211', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
    departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
];


export const MYFLIGHTS: Flight[] = [
    {id: 11, flightNumber : 'FS1298', origin: 'LAX', destination : 'LHR', departDay : 'Thursday',
     departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 99.99},
    {id: 12, flightNumber : 'FS1201', origin: 'LAX', destination : 'LHR', departDay : 'Friday',
     departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 99.99},
];



export const FLIGHTS_25: Flight[] = [
  {id: 1, flightNumber : 'FS1', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 2, flightNumber : 'FS2', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 3, flightNumber : 'FS3', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 4, flightNumber : 'FS4', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 5, flightNumber : 'FS5', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 6, flightNumber : 'FS6', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 7, flightNumber : 'FS7', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 8, flightNumber : 'FS8', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 9, flightNumber : 'FS9', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 10, flightNumber : 'FS10', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 11, flightNumber : 'FS11', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 12, flightNumber : 'FS12', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 13, flightNumber : 'FS13', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 14, flightNumber : 'FS14', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 15, flightNumber : 'FS15', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},    
  {id: 16, flightNumber : 'FS16', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 17, flightNumber : 'FS17', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 18, flightNumber : 'FS18', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 19, flightNumber : 'FS19', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 20, flightNumber : 'FS20', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',  
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 21, flightNumber : 'FS21', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
{id: 22, flightNumber : 'FS22', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
{id: 23, flightNumber : 'FS23', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 24, flightNumber : 'FS24', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 25, flightNumber : 'FS25', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},

];


export const FLIGHTS_43: Flight[] = [
  {id: 1, flightNumber : 'FS1', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 2, flightNumber : 'FS2', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 3, flightNumber : 'FS3', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 4, flightNumber : 'FS4', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 5, flightNumber : 'FS5', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 6, flightNumber : 'FS6', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 7, flightNumber : 'FS7', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 8, flightNumber : 'FS8', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 9, flightNumber : 'FS9', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 10, flightNumber : 'FS10', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 11, flightNumber : 'FS11', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 12, flightNumber : 'FS12', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 13, flightNumber : 'FS13', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 14, flightNumber : 'FS14', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 15, flightNumber : 'FS15', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},    
  {id: 16, flightNumber : 'FS16', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 17, flightNumber : 'FS17', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 18, flightNumber : 'FS18', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 19, flightNumber : 'FS19', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 20, flightNumber : 'FS20', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 21, flightNumber : 'FS21', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 22, flightNumber : 'FS22', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 23, flightNumber : 'FS23', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 24, flightNumber : 'FS24', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 25, flightNumber : 'FS25', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},    
  {id: 26, flightNumber : 'FS26', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 27, flightNumber : 'FS27', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 28, flightNumber : 'FS28', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 29, flightNumber : 'FS29', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 30, flightNumber : 'FS30', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 31, flightNumber : 'FS31', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 32, flightNumber : 'FS32', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 33, flightNumber : 'FS33', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 34, flightNumber : 'FS34', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 999.99},
{id: 35, flightNumber : 'FS35', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},    
  {id: 36, flightNumber : 'FS36', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 37, flightNumber : 'FS37', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 38, flightNumber : 'FS38', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 39, flightNumber : 'FS39', origin: 'LHR', destination : 'NRT', departDay : 'Wednesday',
departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
{id: 40, flightNumber : 'FS40', origin: 'NRT', destination : 'LHR', departDay : 'Thursday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 699.99},
  {id: 41, flightNumber : 'FS41', origin: 'LAX', destination : 'LHR', departDay : 'Monday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 199.99},
  {id: 42, flightNumber : 'FS42', origin: 'LAX', destination : 'LHR', departDay : 'Tuesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 499.99},
  {id: 43, flightNumber : 'FS43', origin: 'LHR', destination : 'ARN', departDay : 'Wednesday',
  departTime : '09:00', arriveDay : 'Monday', arriveTime : '09:00', price : 399.99},
];
